language: python
python:
    - 2.6
    - 2.7
    - pypy
    - 3.2
    - 3.3
    - 3.4
    - pypy3

env:
    - DEPS=true
    - DEPS=false

install:
    - pip install -r requirements.pip
script:
    - python checkout.until.payment.py

before_script:
    # ...

    - "export DISPLAY=:99.0"
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
    - "wget http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar"
    - "java -jar selenium-server-standalone-2.45.0.jar > /dev/null &"
    - sleep 5
